export type ErrorMapType = {
    "LOGIN": {
        "DEVICE_IS_NOT_SECURE": string;
        "INVALID_SESSION": string;
        "MAX_ATTEMPTS": string;
        "ACCESS_BLOCKED": string;
        "IS_NOT_AN_MEMBER_AND_DOESNT_HAVE_ACTIVE_PRODUCTS": string;
        "IS_NOT_AN_MEMBER_AND_HAS_ACTIVE_PRODUCTS": string;
        "NEED_AUTHENTICATION_BY_MP": string;
        "ACCESS_BLOCKED_BY_MP": string;
        "UNKNOWN_ERROR_BY_MP": string;
        "DEVICE_IS_NOT_SECURE_LIMIT_ATTEMPTS": string;
        "DEVICE_IS_NOT_SECURE_UNKNOWN_ERROR": string;
        "OTHERS": string;
    }
};

export const ERROR_MAP: ErrorMapType = {
    "LOGIN": {
        "DEVICE_IS_NOT_SECURE": "DISPOSITIVO_NO_SEGURO",
        "INVALID_SESSION": "SESIÓN_INVÁLIDA",
        "MAX_ATTEMPTS": "MÁXIMO_DE_INTENTOS",
        "ACCESS_BLOCKED": "ACCESO_BLOQUEADO",
        "IS_NOT_AN_MEMBER_AND_DOESNT_HAVE_ACTIVE_PRODUCTS": "NO_ES_MIEMBRO_Y_NO_TIENE_PRODUCTOS_ACTIVOS",
        "IS_NOT_AN_MEMBER_AND_HAS_ACTIVE_PRODUCTS": "NO_ES_MIEMBRO_Y_TIENE_PRODUCTOS_ACTIVOS",
        "NEED_AUTHENTICATION_BY_MP": "NECESITA_AUTENTICACIÓN_SEGÚN_MONITOR_PLUS",
        "ACCESS_BLOCKED_BY_MP": "ACCESO_BLOQUEADO_POR_MONITOR_PLUS",
        "UNKNOWN_ERROR_BY_MP": "ERROR_DESCONOCIDO_POR_MONITOR_PLUS",
        "DEVICE_IS_NOT_SECURE_LIMIT_ATTEMPTS": "DISPOSITIVO_NO_SEGURO_Y_MÁXIMO_DE_INTENTOS",
        "DEVICE_IS_NOT_SECURE_UNKNOWN_ERROR": "DISPOSITIVO_NO_SEGURO_Y_ERROR_DESCONOCIDO",
        "OTHERS": "OTROS"
    }
};
